name: Validate PR
on:
  pull_request:
    types: ['opened', 'ready_for_review', 'reopened', 'synchronize']
    branches:    
      - 'develop'
jobs:
  pr_labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PR Codeowner Autolabel
        id: pr-codeowner-autolabel
        uses: mdzhang/pr-codeowner-autolabel-action@v0.0.3
        with:
          file-path: .github/CODEOWNERS
          repo-token: ${{ secrets.GH_TOKEN }}
          labels-to-owners: |
            {
              "team1": "@akhtech/team1",
              "team2": "@akhtech/team2",
              "team3": "@akhtech/team3"
            }
